### ISSUE TITLE
Implement per-event crew membership.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#100]
Implement per-event crew membership. This should be done by adding a "eventId" field to the memberOf table.

**Comment by halvors** [comment]
I think it's a nice thing that crew members also have to re-apply for each event.

**Comment by petterroea** [comment]
Warbo doesn't want this. He wants to be able to kick out the ones we want gone instead. Talk to warbo about it, i agree with you.

**Comment by halvors** [comment]
Maybe add a "Copy last event crew to current event crew" function to solve this?

**Comment by halvors** [comment]
Added eventId field to memberof table in database, just so we make sure that we the information about who was memboer of what event.

**Comment by halvors** [comment]
Check that accepted applications places member in current event on approval. Also prevent applications from former events from being acceptrd, rejected or queued.

**Comment by petterroea** [comment]
>Maybe add a "Copy last event crew to current event crew" function to solve this?

This sounds acceptable, but talk to warbo about it. We are beginning to add tonnes of new features without even asking warbo if he wants it

**Comment by halvors** [comment]
Asked @Warbo- before i submitted this issue. He was all for it :) One of the reasons is that we need to have backlog on who was a member of the crew. We get economical support by how many participants and crew members under the age of 20 we had last year.
