### ISSUE TITLE
Remove nickname and use username in it place?

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#101]
I think usernames should function as nicknames as well. A user has username, email and phone number to use for login. Do we really need nickname?

Also nickname makes it hard to manage users thru the crew site because most users refer to the username, but all crew site user spesific things like search etc, only care about nicknames.

Also if a user absolutly want his gaming nick, he can change his username :)

**Comment by petterroea** [comment]
This makes sense now. Ask warbo

**Comment by halvors** [comment]
Yeah, you agree that it's kinda over lapping?

**Comment by halvors** [comment]
@Warbo- Does you approve on this?

**Comment by halvors** [comment]
Talked to @Warbo- about this, what we will do is to let it stay. But use username instead of nickname in User::getDisplayName() which is used everywhere. This because it's hard to identify users when firstname, lastname and nickname not are unique.

But nickname is still relevant for compo stuff, so @petterroea you should use the function User::"Comming soon"() instead for the compo stuff.

**Comment by halvors** [comment]
Implemented in commit 4b00f265a783f2d597b78a6dce0117cf2a50d17a

**Comment by halvors** [comment]
Leaving this open until @petterroea is finished changing the needed changes in InfectedCompo.

**Comment by halvors** [comment]
Changed in site.php on InfectedCompo closing this.

**Comment by petterroea** [comment]
GetCompoDisplayName sounds very hacky. Would prefer uniform display of users across the site. I get your point though.

**Comment by halvors** [comment]
Yeah i know. But warbo doesn't want that for the compo site. Better using usernames almost everywhere than nicknames everywhere :)
