### ISSUE TITLE
Implement spreadsheet generator script that makes memberlist for the selected year.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#102]

**Comment by halvors** [comment]
Implemented the SQL stuff and simple table in commit 59e2652dcd7e973344bc913dc62599b77113c6dc

**Comment by halvors** [comment]
Done, but postponing spreadsheet download, se branch yearlist.

**Comment by petterroea** [comment]
How are you outputting table data?

**Comment by halvors** [comment]
Huh? Fetching users and creating a list?...
