### ISSUE TITLE
Implement localization system, so that we can centralize common strings.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#103]
Implement localization system, so that we can centralize common strings. And for the future, maybe implement a localization system.

**Comment by halvors** [comment]
More like centrialize common string like "You are not logged in." and "You don't have permission to this.".

**Comment by halvors** [comment]
This is kinda needed, it will also eliminate silly typoes everywhere :+1:
@petterroea Any ideas how to implement this? Simple manager that holds an array that we reference to with a string like:
```
Localization::getLocale("user_not_logged_in");
```

Or do you have another solution for this? We could also later potentially add translations to this.

**Comment by petterroea** [comment]
Isn't this discussed in another issue? That merge request?

**Comment by petterroea** [comment]
Anyways, my idea would be to have a json file for each language, where each file would have a structure like:

```[ { "user_not_logged_in": "Du er ikke logget inn!"} ]```

Then we have one file as a fallback(norwegian), and bam, a centralized system. The

```Localization::getLocale("user_not_logged_in");```

Sounds like a great way of using it

**Comment by halvors** [comment]
See #144
