### ISSUE TITLE
When uploading wrong image format in json/avatar/uploadAvatar.php it returns an NPE error.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#112]
When uploading wrong image format in json/avatar/uploadAvatar.php it returns an NPE error.

**Comment by petterroea** [comment]
Known, yeah.

**Comment by halvors** [comment]
@petterroea You fix this?

**Comment by petterroea** [comment]
It's on the list, yes

**Comment by halvors** [comment]
@petterroea Is this done?

**Comment by petterroea** [comment]
Hmm... I'l have a look

**Comment by petterroea** [comment]
Closed due to no way to reproduce error atm. I made the errors a bit more user friendly as well, so if it happens again, hopefully the user will go "Oh, something went wrong" and contact us.
