### ISSUE TITLE
Implement support for changing objects in memory and then submit it to the database.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#116]
This would allow functions like User->setUsername ($username) and UserHandler::updateUser ($user)

**Comment by halvors** [comment]
Hmm. This was some crazy idea for simplicity i had. Think it's not benefitical to do this.
We're keeping the current design for now.

**Comment by petterroea** [comment]
I like the idea, but low pri it.

**Comment by petterroea** [comment]
This could be related/done at the same time as #141

**Comment by halvors** [comment]
Closing, doing this on #141
