### ISSUE TITLE
Compo chiefs should be able to delete teams

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#119]

**Comment by halvors** [comment]
Implemented API for this in commit 05eb86302be9b0f52f429a1ae21b434d2848d7a9

**Comment by halvors** [comment]
Implemented in commit 05eb86302be9b0f52f429a1ae21b434d2848d7a9

**Comment by halvors** [comment]
@petterroea Should we close this? Can you create an issue at InfectedCompo so that you're sure that this is actually gonna be implemented in the InfectedCompo site?

**Comment by halvors** [comment]
This needs to be implemented in InfectedCompo, see InfectedLan/InfectedCompo#11
