### ISSUE TITLE
Implement application advisor, so it shows if user has applied for muliplie crews.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#121]
Implement application advisor, so it shows if user has applied for muliplie crews. And if the user was in a crew last event eventually.

**Comment by petterroea** [comment]
So basically "Make the application manager better"?

**Comment by halvors** [comment]
Yeah, but showing information about previous applications as well.

**Comment by halvors** [comment]
Implemented in commit InfectedCrew/a40969e9fbd95be8619b9728092b79a2d0106a8a
