### ISSUE TITLE
Implement sockets for compo

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#124]

**Comment by halvors** [comment]
Hmmmmmm... This is an external service outside apache right?

**Comment by petterroea** [comment]
Sadly, for now :/

BUT!

I think it is doable in php! :D

Mabe research if it is possible to do it in apache?

**Comment by halvors** [comment]
I think implementing this in PHP then run the php script in background independently of apache2 is the way to go. But if we do write this in php, integration with existing code will be easy.

**Comment by petterroea** [comment]
yep. That is the current plan

**Comment by halvors** [comment]
The status here is that we have some issues sharing sessions between Apache2 and cli based PHP, right?

**Comment by petterroea** [comment]
Correct! I am pretty sure the issue is that php does not want to open sessions by another user, and that it is purposedly buildt into php. I'l see what i can do to run it as the apache user.

**Comment by halvors** [comment]
This is done or?

**Comment by petterroea** [comment]
Sockets is implemented, but there is some bugs that i need to test. WIll re-visit it next week, when i have done some more critical stuff.

**Comment by petterroea** [comment]
So, not yet done

**Comment by petterroea** [comment]
Websocket system works. Ish. Randomly fails on some machines, no idea why
