### ISSUE TITLE
Improve performance of database queries.

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#125]

**Comment by halvors** [comment]
I've done some indexing of the database used on development.
This should increase performance. Because often looked up columns does now have an index entry.

**Comment by petterroea** [comment]
mhm

One thing though;

When we do some optimised sql, we should have some way of documenting that "Hey, this is optimised SQL! Don't touch it!" so nobody goes like "oh, this is misplaced. I'l move it to a handler"

**Comment by halvors** [comment]
Um. Well SQL is mostly optimized by indexing tables, and that's nothing to do with our code.

And talking about the code, SQL stuff still goes in the handlers.

**Comment by petterroea** [comment]
Im talking about scenarios where we write non-object oriented sql code to make things faster.

**Comment by halvors** [comment]
Writing non-object oriented code would help in that matter, optimizing the existing code would.

**Comment by petterroea** [comment]
huh?

**Comment by halvors** [comment]
It's not the code that is the problem, but how much we're quering the database.

**Comment by petterroea** [comment]
Yes, and our sollution earlier has been ditching a lot of beautifull object-oriented apicode for a sql query.

**Comment by halvors** [comment]
Yeah, most if the optimization is the use if indexes. But also the fact that i've gone thru all the SQL query code and optimized it. Especially before when we was querying the a list of user by getting all the ids of the users we wanted, and afterwards query each individual user. This is a huge bottleneck.

I'm gonna go ahead an close this now, as all the needed changes here is already done.
We should reopen this if we're experiencing similar issues again...

**Comment by halvors** [comment]
Go thru the all the indexes once again and update according to recent changes.

**Comment by halvors** [comment]
Done.
