### ISSUE TITLE
Make EventHandler::getCurrentEvent() last out the day the event ends.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#129]

**Comment by halvors** [comment]
Fixed in commit d484d8a86404a6195bd04c92d432984ee51aaee3

**Comment by petterroea** [comment]
I would actually suggest a week after. Allways nice having a cooldown after the event.

**Comment by halvors** [comment]
Well, the rest of the day will do. As the EventHandler::getCurrentEvent() is used to determen the ticket information etc on the InfectedMain page.
