### ISSUE TITLE
Implement per-event user permissions.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#131]
Implement per-event user permissions. But make it an alternative to set zero in the "eventId" field. So that some user may have global permissions for all events.

**Comment by halvors** [comment]
Eventually to this is to allow a user only to use his permissions if he is a group member or has permission "*".

**Comment by halvors** [comment]
As of commit

**Comment by halvors** [comment]
It's unclear exactly how we're gonna implement this, an alternative solution is to require that a user is a member of a group in order to use his additinal privileges. Excepts "'*" of course.

This whould be pretty simple to implement, just add an if check in the hasPermission() function of user.

**Comment by halvors** [comment]
Implemented solution in commit 5622b47c21f65b345e598ac161f8a6d3795b5a42

**Comment by petterroea** [comment]
Yes, this is a must.
