### ISSUE TITLE
Implement group history.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#132]
Group history, whould allow us to look at a crew members history, when he/she have been at the event, and in what crew they have been in.

**Comment by petterroea** [comment]
On the users page?

**Comment by halvors** [comment]
Yes. Or maybe an general log that lists all group members and when they joined?

**Comment by petterroea** [comment]
![http://puu.sh/gaP98/f0975b2fd9.jpg](http://puu.sh/gaP98/f0975b2fd9.jpg)

**Comment by petterroea** [comment]
Something that lets you look back at events and see a short summary of crew members for it would also be cool stuff.

**Comment by halvors** [comment]
Implemented in commit f7f6e476e06f718e7834d6641250784928df72a3
