### ISSUE TITLE
Header set Access-Control-Allow-Origin "*" is unused?

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#137]
As far as i remember, this was used to try cross domain json. Turns out we was going for the includepath solution instead. So this could be removed now i belive. What do you think @petterroea?

```
Header set Access-Control-Allow-Origin "*"
```

**Comment by petterroea** [comment]
Yeaaah, i think it is unused. Try removing it on test.infected.no and see if something breaks :smile:

**Comment by halvors** [comment]
If it breaks it should just be the sessions.

**Comment by halvors** [comment]
Removed, nothing changed.
