### ISSUE TITLE
Use json_encode()'s pretty print.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#138]
echo json_encode($json, JSON_PRETTY_PRINT);

**Comment by halvors** [comment]
Implemented in commit 5f1c13b3f4bf3435c666f017f17595bd0fb8acb9

**Comment by petterroea** [comment]
Sweet. Are my days of using a online formatter tool over now? :smile:

**Comment by halvors** [comment]
Yes.
