### ISSUE TITLE
Class 'EventObject' not found

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#142]
This seems to be affecting a lot of scripts. This needs to be fixed, everything seems to be just ok.

```
PHP Fatal error:  Class 'EventObject' not found in /home/test.infected.no/public_html/api/objects/team.php on line 27
```

It seems to cause more errors than just in the team.php file as well.

It seems like this may be caused when eventobject.php is required in a object file then the object file is required in the handler and then the object requires the handler again. But not sure. We really needs to sort out this before next release, and actually ASAP.

**Comment by halvors** [comment]
@petterroea Can you take a look at this?

**Comment by petterroea** [comment]
wtf is this.

This is the include bug you talked about on the train, right? Do we know when it started happening?

**Comment by halvors** [comment]
No. We don't. It doesn't make any sense to me. Everything seems ok.

**Comment by halvors** [comment]
I finally figured this out. Seems that the file on the webserver somehow was corrupted. So even when uploading a new one and overwriting the bugs persisted.

I finally made it work when deleting and then reuploading the 'eventobject.php' file.
