### ISSUE TITLE
Lot of the compo backend uses timestamps as integer, this should be converted to datetime when stored in database.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#152]

**Comment by petterroea** [comment]
Yes, i know. I suggest we go over and refactor some time after next infected. Am trying to remember to use mysql dates atm.

**Comment by halvors** [comment]
To format data for output use:
```
date ('Y-m-d H:i:s', $yourtimevariablefromdatabasehere)
```

For getting current time to put into a SQL query do:
```
time()
```

**Comment by halvors** [comment]
There should be no use of timestamps anymore afaik.

**Comment by petterroea** [comment]
Sweet. Please bug me about it if i forget.
