### ISSUE TITLE
Cleanup the compo database, lot of stuff here should be event specifiec.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#153]
Cleanup the compo database, lot of stuff here should be event specifiec.

We want to keep history but at the same time not show data to the user from former events.

And by this i mean especially the memberof, participantof etc tables.

**Comment by halvors** [comment]
@petterroea You designed the database layout here. Could you explain how and what information that should be keept from former events?

What tables need a "eventId" field and implementation code wise?

**Comment by petterroea** [comment]
A lot. I'l have a look at it

**Comment by halvors** [comment]
Postponing this until 0.4, when you write more features here you could add it at the same time.

**Comment by petterroea** [comment]
Little is event specific on compo. A compo itself is event specific, and everything else is compo specific. No skipping up the hierarchy

**Comment by petterroea** [comment]
Things look properly designed as of now. We can re-assess when the time for refactors comes.
