### ISSUE TITLE
CompoHandler::getClans(Compo $compo) moved to ClanHandler::getClansByCompo(Compo $compo)

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#156]
CompoHandler::getClans(Compo $compo) is moved to ClanHandler::getClansByCompo(Compo $compo).

CompoHandler::getClans(Compo $compo) is kept as a wrapper for compatibility but should be removed as soon as possible.

**Comment by petterroea** [comment]
A clan only has one compo, and should therefore be consithered a child of compo. I think it would be wrong to have getClansByCompo in the clanhandler, as the compo handler should give you the list of clans that use it
