### ISSUE TITLE
CompoHandler::getCompleteClans(Compo $compo) is moved to ClanHandler::getCompleteClansByCompo(Compo $compo)

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#157]
CompoHandler::getCompleteClans(Compo $compo) is moved to ClanHandler::getCompleteClansByCompo(Compo $compo)

CompoHandler::getCompleteClans(Compo $compo) is kept as a wrapper for compatibility reasons.

**Comment by petterroea** [comment]
This would be wrong, as a clan only has one compo, and should be looked as a "child" in this perspective

**Comment by halvors** [comment]
Basically stuff that "SELECT * FROM clan" should go in clanhandler.

**Comment by petterroea** [comment]
np
