### ISSUE TITLE
ClanHandler::getCompo(Clan $clan) moved to CompoHandler::getCompoByClan(Clan $clan) 

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#158]
ClanHandler::getCompo(Clan $clan) moved to CompoHandler::getCompoByClan(Clan $clan) 

ClanHandler::getCompo(Clan $clan) is kept as a wrapper for compatibility reasons.

**Comment by petterroea** [comment]
No, this is incorrect, as a clan only has one compo, and is therefore compo specific.

**Comment by halvors** [comment]
No it's still correct. We onlt tell in compohandler what compo we want by which clan.

**Comment by petterroea** [comment]
![http://puu.sh/ica4R/47b8457e0e.jpg](not fuko)
