### ISSUE TITLE
Add friend system?

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#179]
Add friend system? Where users will be able to see each other on the seatmap, and possibly share other things somehow.

**Comment by petterroea** [comment]
Also, benefit api :smile:

**Comment by halvors** [comment]
Haha, i don't thinks so.

**Comment by halvors** [comment]
This is almost implemented, @petterroea will you do the seatmap stuff? Think the orange or blue color can be used for friend seats.

**Comment by petterroea** [comment]
Yes, i can write an interface for it on tickets.

From what i understand, you can simply add whoever you want as a friend. Could you add a "request system", where you would send a friend request, and when the reciever accepts it, both are mutual friends? I suggest this for 0.5.

**Comment by halvors** [comment]
@petterroea Yeah, for simplicity i think just adding a "accepted" field to the friends table would do the trick. No need for splitting this into 2 tables.

**Comment by petterroea** [comment]
That was a much better implementation, i agree.

**Comment by halvors** [comment]
This is implemented, closing issue.
