### ISSUE TITLE
Internal log system

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#181]
Here is the issue:

We have no idea what is happening except for exceptions. If some user gets a soft error(where we catch the error and display a message), they get annoyed, and we don't even know it is happening!
Also, we could log stuff like ticket sales, registered users, and that kind of stuff.

**What i suggest**

I suggest a log system where we have a database that looks like this:

`id, time, severity, system, message, file, additionalData, user, event`

Severity could be f.ex a number from 0-5 depending on how bad it is, and system could be a word that describes what part of the website that is talking(f.ex `api`, `json`, `compo`, `payment`, etc). Message would be some meaningfull message explaining what is happening. File would be the php file generating the message, and additionalData would be a json object containing additional information about the message if any. These two fields would really help debugging. User would be the currently logged in user, or null if none. The event field sounds smart, as we aren't really interrested in things from an old event unless we explicitly say so.

What we need to do is research if we are allowed to log that specific information, and then implement that, and some gui. I can also imagine a notification on the crewsite for admins saying "X severe errors have happened the past 24 hours" or something. 

For the future, catching errors and logging them could also be usefull, as having the errors in a proper format would be a lot better then going to webmin or error_log(and it is very easy to catch errors!).

But for now, a system for logging things happening would be really usefull.

**Comment by petterroea** [comment]
Setting as high priority because i think it is.

**Comment by halvors** [comment]
Think we should postpone to next event and set low priority.

**Comment by petterroea** [comment]
I disagree at setting it to low-pri, as i really wish i had this for the ticket sale this year. 
However, i do agree we can postpone.

**Comment by halvors** [comment]
30 tickets left, so maybe postpone then? And you should implement this right after infected, instead of waiting to 1 week before next ticket sale.

**Comment by petterroea** [comment]
Yes, postpone to next infected. I'l have a look at it when i can.

**Comment by petterroea** [comment]
But, do you agree that we make a database where we store logged data? And that i implement it in f.ex soft errors in the json api?

**Comment by halvors** [comment]
Not exactly. But this is low priority, it's nice to have. But i suspect that it will cause more errors than it would solve.

**Comment by petterroea** [comment]
Simple version of this implemented for payment
