### ISSUE TITLE
People's permissions and teams are being moved around

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#182]
I think something is gone during migration:

 * People's permissions are changed when data is migrated. Everyone who had the same old permission gets the same new permission, so i think the issue is some kind of offset glitch
 * People's teams are changed. Might also be offset glitch.

**Comment by halvors** [comment]
Shouldn't be. The migration is simply copying of rows where "eventId" is replaced with the new event, no iteration here.

**Comment by petterroea** [comment]
Well, there is an issue anyways. Can you have a look at it?

**Comment by petterroea** [comment]
Talk to @Warbo- if you want more details

**Comment by halvors** [comment]
Not right now, maybe next week. But i suspect this to be an issue related to earlier manual event migration.

**Comment by halvors** [comment]
This is now solved.
