### ISSUE TITLE
Increase avatar upload filesize

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#185]
This because images are in some cases larger then our current limit, and they are downscaled and compressed by the cropper anyways, so it won't be there for long.

I suggest we up it to 30 MiB.

Places that need changing:
 * Settings.php
 * .htaccess in Api

If the numbers do not match, the user will get a cryptic "we got an unknown upload error: 1. Please tell our technicians about this" or something like that, message.

**Comment by halvors** [comment]
Make it 32MB, and sure go ahead.

**Comment by halvors** [comment]
@petterroea Are you sure need to change things in Settings.php, only resolution stuff is handled there.

**Comment by petterroea** [comment]
Hmm? I am pretty sure.

**Comment by halvors** [comment]
@petterroea I can take this task, if it's ok with you :)

**Comment by halvors** [comment]
Done.

**Comment by petterroea** [comment]
Sweet stuff, what commit?
