### ISSUE TITLE
Last minute compo API change, broke InfectedMain.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#188]
Last minute compo API change, broke InfectedMain.

PHP Fatal error:  Call to undefined method Compo::getMode() in /home/infected.no/public_html/main/v7/pages/competitions.php on line 38, referer: https://infected.no/v7/

**Comment by petterroea** [comment]
Oh yeah. Fuck. My responsibility, i'l fix it

**Comment by halvors** [comment]
Good :)

**Comment by halvors** [comment]
Just a matter of calling the right functions from the InfectedMain page.

**Comment by petterroea** [comment]
Yeah, mode will be replaced by $compo->teamSize() . "v" . $compo->teamSize()

So simple fix. I just can't get main running locally :dancer:

**Comment by petterroea** [comment]
@halvors Warbo said you fixed this, is it true?

**Comment by halvors** [comment]
Yeah. Closing the issue.
