### ISSUE TITLE
Make some module system for the websocket server, and port getCompoStatus

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#189]
getCompoStatus is a trainwreck of heavy api access. Let's replace it with websockets :)

Because we are no longer only doing chat with the web socket system, i will also make it into a module based system. This will be fun

**Comment by halvors** [comment]
Sounds good!

**Comment by petterroea** [comment]
Should be refactored, but atm, we expect the user to be logged in. Is it worth the time refactoring to support websockets without being logged in?

The whole website works on being logged in, except for the main page.

**Comment by petterroea** [comment]
This was done
