### ISSUE TITLE
Rewrite how we organize groups, teams, and membership of those per event

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#196]
Rewrite how we organize groups, teams, and membership of those per event.

My proposal is that we make memberof table the only one having an eventId. And have teams only reference their respectable group, not chief's. And make membership per event based on the eventid in memberof table.

This way we can still have per event membership without the hassle of losing database consistensy and having to manually migrate between events.

On thing that we also may do is to add an "active" field to a group so that it only is deactivated when "deleted" in frontend. And so on keeping the record in database for history.

**Comment by petterroea** [comment]
So basically, keep all data about groups and teams, but have memberships automatically expire? I like it.

**Comment by halvors** [comment]
@petterroea Still thing this is a good idea? Crew names doesn't change that often.

**Comment by petterroea** [comment]
Good job!
