### ISSUE TITLE
Infoscreen api returns no slides when it should, according to event manager dude

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#221]
Should be verified for poor user input, but yes, what it says on the tin.

**Comment by halvors** [comment]
Problem was start time and end time not being set properly, which causes the slide to never appear on the screen. This is now fixed in  7aa885c.

Keep in mind that as of the nature of slides, they only appear in the given timeframe anyway.

**Comment by petterroea** [comment]
awesomesauce
