### ISSUE TITLE
Implement duplication of seatmaps

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#42]
Not gonna do now because lazy, and we dont need the feature until next infected anyways...

**Comment by halvors** [comment]
Postponing this until after current event.

**Comment by petterroea** [comment]
This is haste, as we need a duplicated seatmap for the new event

**Comment by petterroea** [comment]
Will do later tonight

**Comment by halvors** [comment]
Already done manually i think...


-------- Opprinnelig melding --------
Fra: Liam Svanåsbakken Crouch <notifications@github.com> 
Dato:13.01.2015  16:34  (GMT+01:00) 
Til: InfectedLan/InfectedAPI <InfectedAPI@noreply.github.com> 
Ko: Halvor Lyche Strandvoll <halvors@halvors.org> 
Emne: Re: [InfectedAPI] Implement duplication of seatmaps (#42) 

This is haste, as we need a duplicated seatmap for the new event

**Comment by petterroea** [comment]
Can you check?

**Comment by petterroea** [comment]
There is another huuuuuuuuuge bug that will fuck up ticket sales, but i cant recall what it is. Will check some time during evening, currently at work

**Comment by petterroea** [comment]
Oh wow, you did that manually. I am impressed. Ohwell, no longer required.

I started writing the duplication in e9be015c86f1887f9a5053b998a7b6a8536d5911

**Comment by halvors** [comment]
It's highly required. Should be implemented as soon as possible. But you can wait until you got some free time. After the current event parhaps :)

**Comment by petterroea** [comment]
You duplicated it for the coming events though, so it is not really critical until *SECRET_CHANGE* happens that would cause the seatmap to need a redesign.

Still, i am working on it. Will work on it when i have time

**Comment by halvors** [comment]
@petterroea Taking you a loong time?

**Comment by petterroea** [comment]
seatmap duplication works afaik, at least in the editor
