### ISSUE TITLE
Move public function displayWithInfo() and display() from group and team objects to crew site as this is crew specific

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#51]

**Comment by halvors** [comment]
Agh. I really don't wanna touch this. It's a crappy sceary, and probatly some of the oldest code around here :8ball:

**Comment by petterroea** [comment]
What about just assigning it a low-priority tag and let it rot?

**Comment by halvors** [comment]
Done in commit e6edd2f4e11e16ecdb930a14b0e1a35e24a770ad

**Comment by halvors** [comment]
Done in commit e6edd2f4e11e16ecdb930a14b0e1a35e24a770ad

**Comment by halvors** [comment]
Done in commit 7d5ded9ed4a9a195d7a776fd046d5b7ec578fa0e
