### ISSUE TITLE
Re-structure json, objects, and handlers according to feature

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#53]
@halvors mentioned this a while ago, but it wasnt until now i have realised how much we propabily need this. What do you think, @halvors ?

**Comment by halvors** [comment]
Json refactored, postponeing rest of this until 0.3.

**Comment by halvors** [comment]
Should we say that this is done now, or?

**Comment by petterroea** [comment]
I think the handler removal discussion is something we can argue for ages about. Let's discuss ideas, but leave it as it is for now

**Comment by petterroea** [comment]
So yes, i think we are done for now

**Comment by halvors** [comment]
Ok, closing this for now.
