### ISSUE TITLE
Cleanup the rest of json folder

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#60]
Can you cleanup your files in the json folder?

Here is the files that should be renamed to a better describing name and moved to a folder:
![skjermbilde](https://cloud.githubusercontent.com/assets/620303/5376874/cedbed6c-807b-11e4-8075-3649148b49e4.PNG)

**Comment by petterroea** [comment]
No, working on it

**Comment by halvors** [comment]
Finished now?

**Comment by petterroea** [comment]
Still on it. Working slowly but steady.

Am getting progress though. Give me until friday :)

**Comment by halvors** [comment]
Ok.

**Comment by halvors** [comment]
Time's up :P Is this done now?

**Comment by petterroea** [comment]
Headache has stopped me from being productive today. Will look at it tomorrow morning

**Comment by halvors** [comment]
Yeah closing this now?

**Comment by halvors** [comment]
Nice :)
