### ISSUE TITLE
Remove SQL code from avatar object

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#66]

**Comment by halvors** [comment]
I see no problem leaving this to the handlers. The idea is that handlers is "the gateway" to the database. Keeps it simple to have the SQL stuff in there. I think we should just stick with this solution and move the SQL stuff to the handlers.

**Comment by petterroea** [comment]
Yeah. It does mean the codebase is huger, though, and you need more tabs open in your IDE to work on one feature, possibily slowing productivity

**Comment by halvors** [comment]
Implemented in commit 7c9a8c9e5c354cb4a8c4093eb9bd1cf9e2a0b0d2
