### ISSUE TITLE
Avatar uploading code is still pretty buggy.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#72]
Avatar uploading code is still pretty buggy. Maybe we should shrink down on the quality? 1200x900 is a pretty big image.

**Comment by halvors** [comment]
@petterroea Can you take a look at this? This is priority as crew applications starts around now.

**Comment by petterroea** [comment]
Tested the uploader in google chrome. Found some stuff

**Comment by petterroea** [comment]
Repoen if it is still a problem
