### ISSUE TITLE
Add ClanMember

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#81]
Because we now need to keep track of who is stepin and who is playing in a clan(compo), i/we have to add an object called ClanMember that references a user, and it's state.

Making ticket on it to remind me, i am tired and can not write functional code until later this week(or mabe today. We will find out sooner or later)

**Comment by halvors** [comment]
Are you going to implement this @petterroea?

**Comment by petterroea** [comment]
No, i coded a workaround. Thanks for reminding me.
