### ISSUE TITLE
Fix changes due to new php update

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#82]
I don't really know what is causing it, and i don't know what php version is affected, but some new php version the newest wampserver is using is disliking our code, due to how php handles passing variables to a function.

Here is an example that crashed on my local wamp environment:

objects/Ticket.php line 116 *original code*
```
$eventName = !empty($event->getTheme()) ? $event->getTheme() : $season . date('Y', $event->getStartTime());
```

*fix code*

```
$theme = $event->getTheme();
$eventName = !empty($theme) ? $theme : $season . date('Y', $event->getStartTime());
```

Some new php version is not liking that we are passing a function as an arguments, propabily handling it as a variable or something. I suggest we look at removing occurances of it. I will personally fix when i run over it in my local testbox, but i will make this ticket so @halvors also sees it

**Comment by halvors** [comment]
I don't think this is an update, just you running in a more restrictive enviroment.

**Comment by petterroea** [comment]
This looks like php is reading the code differently, so i don't think that is the case

**Comment by halvors** [comment]
No it doesn't, i don't have this problems on exactly the same version.

**Comment by halvors** [comment]
Things are up and running now right? Closing this, just reopen if this is still a problem.
