### ISSUE TITLE
Add support for mass mail

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#86]
We should be able to mass mail participants from:

 * Current event
 * Last 2(?) events.

This could be used for promotion to old participants, and info for current participants

**Comment by halvors** [comment]
Well, mass mailing all participants doesn't better out reputation in all worlds mail servers. Espicially because the emails gonna be send at excactly the same time...

**Comment by petterroea** [comment]
Yeah, i know. Will convey to warbo. Still something to consither for next event, mabe with a "*fuck you if you use this too much*" warning in the UI?

**Comment by petterroea** [comment]
Would a cron job sending a mail every 5 minutes fix the problem?

**Comment by halvors** [comment]
It's kinda hacky. Think we'll just skip scheduled mass mail and implement mass mail in general.

**Comment by halvors** [comment]
Are you working on this or should i?

**Comment by petterroea** [comment]
I am not working on it,, as it is not priority. It is a "nice to have" for next infected, according to warbo.

I agree cron would be hacky, but what really matters is that it works :smile:

**Comment by halvors** [comment]
Implemented in commit 63408e84536b67267b82312d7ad3225be106affb
