### ISSUE TITLE
Fix so that findUser queries all words in a string when there is spaces in it.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#87]
Fix so that findUser queries all words in a string when there is spaces in it.
Currently we can search on firstname or lastname but not both.

**Comment by halvors** [comment]
I suggest we use explode(' ', $query) to split the string into arrays where there is spaces. And then search for all the values in the list for every field in the database.

**Comment by petterroea** [comment]
Sounds good

**Comment by halvors** [comment]
Hmm. I don't know exactly how we should implement this...

A "explode(' ', $query)" would give an array of all words in the search query. But then we have to search all the words against every columns that is to be queried.

Also if we matches every word separatly, we would get this problem case:
> If i search for my own name "Halvor Strandvoll" i'll get matches for everyone named "Halvor" and everyone named "Strandvoll".

We have to think this throught.

**Comment by petterroea** [comment]
There should be some way of doing SELECT * FROM USERS WHERE `firstname` LIKE*$IN_ARRAY$*.

Sql has kickass features. I bet it has something to solve this. 

Of the result set, sort by relevance(if first name and surname matches, etc. More points for maching surname to query)

**Comment by halvors** [comment]
Also, searching by email doesn't work. I wounders why...

**Comment by halvors** [comment]
@zenoy Can you take a look and try figure this out? :)

**Comment by petterroea** [comment]
@zenoy ! @zenoy !

**Comment by halvors** [comment]
This is high priority, should be implemented as soon as possible.

**Comment by halvors** [comment]
Think we're going to use fulltext indexes on this.

See: http://dba.stackexchange.com/questions/39983/how-can-i-search-for-a-name-in-two-columns-in-mysql

**Comment by halvors** [comment]
Implemented by using Full-Text search in commit 44742c0a8833c29bbd51b5254f0d839de7f2cb75
