### ISSUE TITLE
Add "Only mail those with more then 1 ticket" to the mass mail system

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedAPI#88]
@Warbo-  wants us to add a feature to the mass-mail system allowing him to mass-mail only users with more then 1 ticket, so he can say stuff like "Move your tickets to the proper owner so you dont have to go into the "special needs" queue at checkin".

@halvors You have control of that code base now. Can you have a look at it? Mabe we should make it a bit more generic, like f.ex you could "build" a query to select users to mail with?

**Comment by halvors** [comment]
Implemented in commit c29ca1292b5e90bbc8ba582f0915db9e005d015d.

**Comment by halvors** [comment]
Can you help me verify that this option "allWithTickets" actually work. I had a hard time setting up a testcase for this on my own. But first, take a look at my commit. It seems to be just ok right?

**Comment by petterroea** [comment]
I'l revise it on the train later today.

**Comment by petterroea** [comment]
Yep. Code looks ok.

For testing: make a user with a 10minutemail account. Give it 0 tickets. Make sure you only have tickets.

For testing, the allWithTicket should be mailed to us, but not to the test account, allwithTickets should be mailed to only me, and yeah, you get the idea.

**Comment by halvors** [comment]
Yeah. I love php's not strong types. Haha just kidding. Kinda hate it :-)

**Comment by halvors** [comment]
Adding "only those which had a ticket in the period of the last 3 events". Then we can close this.
