### ISSUE TITLE
Fix so that applications that belongs to a user that got avatar image rejected is invalid.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#91]
Fix so that applications that belongs to a user that got avatar image rejected is invalid.

Currently you can upload a image that's not going to be approved, it will be deleted but your application is still gonna be accepted...

**Comment by halvors** [comment]
Hmm... We have to sort this out somehow, think we need some sort of fancy solution here.

Maybe we could make it impossible to accept applications with an invalid avatar, sending an email and forcing the user to reupload another avatar in order for the application to be "acceptable" for the crew chiefs?

**Comment by petterroea** [comment]
Has warbo requested this? It sounds easier to just make the chief nag about it

**Comment by halvors** [comment]
Maybe. I don't see a good way around this.

**Comment by halvors** [comment]
Ok, closing this for now.

**Comment by petterroea** [comment]
I would suggest we only close issues that are resolved, and instead create a "nofix" or similar tag for these kind of issues

**Comment by halvors** [comment]
@petterroea Closing this. It's never happen and we don't want it this way anyway.
