### ISSUE TITLE
Implement a dynamic chatting system.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#93]
Implement a dynamic chatting system. Will be used for compos.

**Comment by halvors** [comment]
CreateChatroom()
GetLastMessages($chatroom, $count), returnerer ChatMessage
GetLastMessageId($chatroom) returnerer id på siste melding i den chatten
AddMember($chatroom, $member)
RemoveMember($chatroom, $member)
IsMember($chatroom, $member)
SendMessag($chatroom, $member, $message)

**Comment by halvors** [comment]
Implemented in commit 252abd2711a6e5d2c8d99ad65fc5faf4bbfe7776

**Comment by petterroea** [comment]
Assigning to me, i will test once i start using it

**Comment by halvors** [comment]
Well, i'm not sure that it's feature complete. If there is something you find out that you need let me know.

But this should meet your initial specifications.

**Comment by halvors** [comment]
Should i close this?

**Comment by petterroea** [comment]
Nah, i'l close when its tested

**Comment by halvors** [comment]
This was merged in commit 233c657163f0f6535cfddaaee688e501b7931bc9, does it work? Closing this now? Remember to create database tables :-)

**Comment by petterroea** [comment]
Aren't they created?

**Comment by halvors** [comment]
It is. Just confirm it :-)

**Comment by halvors** [comment]
@petterroea Did you test this last night? Should we close this issue?
