### ISSUE TITLE
Implement user option to allow people to toggle options.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedAPI#94]
Implement user option to allow people to toggle options. Like hide phone number etc.

**Comment by petterroea** [comment]
Do we need this? I think this should be tagged as a nice-to-have, and not as a milestone. Has warbo asked for it?

**Comment by halvors** [comment]
No. We have to hide i given crew members phone number. And it cannot be just 0 as it is now :O

**Comment by halvors** [comment]
Implemented in commit 7d5bf769affce6b4407607986f347bda26709a80

But still need to be implemented in front-end. But it works to hide users phone number thru the database.
